design_task:
  description: >
    Create a detailed design document in markdown format for the requirement: {requirement}
  expected_output: >
    A simple design document in markdown format.
  agent: development_lead
  output_file: output/{module_name}_design.md

coding_task:
  description: >
    Based on the design provided by the design task, write crisp code in python for a given requirement.
    No clutter and unnecessary commentary please. just the python that we can save as a py file and execute directly should be good enough.
    The requirement is this:
     {requirement}
  expected_output: >
    A python file containing the code for the given requirement.
  agent: backend_engineer
  output_file: output/{module_name}.py
  context:
    - design_task

code_review_task:
  description: >
    Review the python code provided by the backend engineer and ensure it is done according to the design provided by the development lead. The requirement is this : {requirement}
  expected_output: >
    A code review document detailing what was reviewed and what is the outcome.
  agent: code_reviewer
  output_file: output/{module_name}_code_review.md
  context:
    - design_task
    - coding_task

code_rewrite_task:
  description: >
    Incorporate all the comments provided by the code reviewer and rewrite the code generated by the backend engineer. Ensure adherence to design provided by the development lead.
    The requirement is this : {requirement}
  expected_output: >
    A python file containing the code for the given requirement.
  agent: backend_engineer
  output_file: output/{module_name}_improved.py
  context:
    - design_task
    - coding_task
    - code_review_task

code_review_task_2:
  description: >
    Review the python code rewritten by the backend engineer and ensure it is done according to the design provided by the development lead and it incorporates the comments you had provided earlier (if any). 
    The requirement is this : {requirement}
  expected_output: >
    A code review document detailing what was reviewed and what is the outcome.
  agent: code_reviewer
  output_file: output/{module_name}_code_review_2.md
  context:
    - design_task
    - coding_task
    - code_rewrite_task
